#cloud-config

hostname: node1
coreos:
  etcd:
    name: node1
    addr: 192.168.1.196:4001
    bind-addr: 0.0.0.0
    peer-addr: 192.168.1.196:7001
    peers: 192.168.1.197:7001,192.168.1.199:7001
    peer-heartbeat-interval: 250
    peer-election-timeout: 1000
  units:
    - name: static.network
      command: start
      content: |
        [Match]
        Name=ens33

        [Network]
        Address=192.168.1.196/24
        DNS=192.168.1.1
        Gateway=192.168.1.1
#    - name: cbr0.netdev
#      command: start
#      content: |
#        [NetDev]
#        Kind=bridge
#        Name=cbr0
#    - name: cbr0.network
#      command: start
#      content: |
#        [Match]
#        Name=cbr0
#
#        [Network]
#        Address=10.244.1.1/24
#
#        [Route]
#        Destination=10.0.0.0/8
#        Gateway=0.0.0.0
#    - name: cbr0-interface.network
#      command: start
#      content: |
#        [Match]
#        Name=ens34
#
#        [Network]
#        Bridge=cbr0
#    - name: nat.service
#      command: start
#      content: |
#        [Unit]
#        Description=NAT non container traffic
#
#        [Service]
#        ExecStart=/usr/sbin/iptables -t nat -A POSTROUTING -o ens33 -j MASQUERADE ! -d 10.0.0.0/8
#        RemainAfterExit=yes
#        Type=oneshot
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
    - name: download-flannel.service
      command: start
      content: |
        [Unit]
        After=etcd.service
        Before=flannel.service
        Description=Download flannel Binaries
        Documentation=https://github.com/coreos/flannel
        Requires=etcd.service

        [Service]
        ExecStart=/usr/bin/mkdir -p /opt/bin
        ExecStart=/usr/bin/cp /home/chianyu/flanneld /opt/bin/
        ExecStart=/usr/bin/chmod +x /opt/bin/flanneld
        RemainAfterExit=yes
        Type=oneshot
    - name: flannel.service
      command: start
      content: |
        [Unit]
        Requires=download-flannel.service
        After=download-flannel.service

        [Service]
        ExecStartPre=-/usr/bin/etcdctl mk /coreos.com/network/config '{"Network":"10.244.0.0/16"}'
        ExecStart=/opt/bin/flanneld
    - name: docker.service
      command: start
      content: |
        [Unit]
        Requires=flannel.service
        After=flannel.service
        Description=Docker Application Container Engine
        Documentation=http://docs.docker.io

        [Service]
        ExecStartPre=/bin/mount --make-rprivate /
        ExecStartPre=-/usr/bin/ip link set dev docker0 down && /usr/sbin/brctl delbr docker0
        #ExecStart=/usr/bin/docker -d -s=btrfs -H fd:// -b cbr0 --iptables=false
        EnvironmentFile=-/run/flannel/subnet.env
        ExecStart=/usr/bin/docker -d -s=btrfs -H fd:// --bip=${FLANNEL_SUBNET} --mtu=${FLANNEL_MTU}

        [Install]
        WantedBy=multi-user.target
    - name: download-kubernetes.service
      command: start
      content: |
        [Unit]
        After=network-online.target
        Before=kubelet.service
        Before=proxy.service
        Description=Download Kubernetes Binaries
        Documentation=https://github.com/GoogleCloudPlatform/kubernetes
        Requires=network-online.target

        [Service]
        ExecStart=/usr/bin/mkdir -p /opt/bin
        ExecStart=/usr/bin/cp /home/chianyu/kubelet /opt/bin/
        ExecStart=/usr/bin/cp /home/chianyu/proxy /opt/bin/
        ExecStart=/usr/bin/chmod +x /opt/bin/kubelet
        ExecStart=/usr/bin/chmod +x /opt/bin/proxy
        RemainAfterExit=yes
        Type=oneshot
    - name: kubelet.service
      command: start
      content: |
        [Unit]
        After=etcd.service
        After=download-kubernetes.service
        ConditionFileIsExecutable=/opt/bin/kubelet
        Description=Kubernetes Kubelet
        Documentation=https://github.com/GoogleCloudPlatform/kubernetes
        Wants=etcd.service
        Wants=download-kubernetes.service

        [Service]
        ExecStart=/opt/bin/kubelet \
        --address=0.0.0.0 \
        --port=10250 \
        --hostname_override=192.168.1.196 \
        --etcd_servers=http://127.0.0.1:4001 \
        --logtostderr=true
        Restart=always
        RestartSec=10

        [Install]
        WantedBy=multi-user.target
    - name: proxy.service
      command: start
      content: |
        [Unit]
        After=etcd.service
        After=download-kubernetes.service
        ConditionFileIsExecutable=/opt/bin/proxy
        Description=Kubernetes Proxy
        Documentation=https://github.com/GoogleCloudPlatform/kubernetes
        Wants=etcd.service
        Wants=download-kubernetes.service

        [Service]
        ExecStart=/opt/bin/proxy --etcd_servers=http://127.0.0.1:4001 --logtostderr=true
        Restart=always
        RestartSec=10

        [Install]
        WantedBy=multi-user.target
  update:
    group: stable
    reboot-strategy: off
ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHo+5nVpxDhnWBPhEuQ7D7ZYELvA5+fPEWfHmMUwBdW069FSfX1LtbVAUKW7NGMfCxTijQMfvmFt7i+o28uqrVGN+xlDdkKTarPYO/Ux6Rukw0D5RZLVDVdRIOV8Si26pkFp4ezs1NFnCFsPTXD8U4cQ1lok//x248oKGsB4ZWuRNf4PCaIdXDveXdQRbaV5SDo9JEt9VkmfSraH5JENguP51RhFJYzWQAB1QbRZrHYUfZbE+pb/XDTdSPidfRCvss9fDrrhviZjv1Gr8C9jbmSGRB8pKwGC/GWV/mj8nYEY1K3/0c/N9NNIPtmvNkQjq7eGsSUf0cM8ZbwWugr8cB kelseyhightower
